version: "2.0"
services:
  shared:
    extends:
      service: shared
      file: compose-base.yml

  postgres:
    extends:
      service: postgres
      file: compose-base.yml

  phoenix:
    extends:
      service: phoenix
      file: compose-base.yml
    environment:
      MIX_ENV: test
    command: |
      /bin/sh -c "
        mix do deps.get, compile, ecto.create
        while true; do sleep 10; done
      "
    depends_on:
      - postgres
    volumes_from:
      - shared
